### ISSUE TITLE
[Question] - What we should add with Test Path option 

### ISSUE THREAD

**Issue by moatazeldebsy** [DamienBitrise/bitrise-test-plan-sharder#3]
Hi there, 
I'm trying to use this step in our Bitrise workflow and always give me there is no path found. so my question is shall I add the full path for example` Volo/EarGrayUITests/UITests` or the `UITests` folder name only or what exactly , this is an example error: 

```
DEBUG: false
fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, scandir '/Users/vagrant/git/Volo/EarlGreyUITests/UITests'
    at Object.readdirSync (fs.js:790:3)
    at walkSync (/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise443567130/step_src/index.js:120:20)
    at pbxProject.<anonymous> (/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise443567130/step_src/index.js:51:21)
    at pbxProject.emit (events.js:198:13)
    at pbxProject.<anonymous> (/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise443567130/step_src/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Thank You!

**Comment by DamienBitrise** [comment]
Hi,

Is `/Volo` the name of your repo or is it a folder in the root of your repo?

On Bitrise your code gets checked out to `/Users/vagrant/git/` so this is your root folder.

**Comment by moatazeldebsy** [comment]
`Volo` is our Xcode project name, I already added it, you can check in the error 
`$BITRISE_SOURCE_DIR/Volo/EarlGreyUITests/UITests`

and the error displaying : 

``Error: ENOENT: no such file or directory, scandir '/Users/vagrant/git/Volo/EarlGreyUITests/UITests'
`

**Comment by DamienBitrise** [comment]
Can you share your bitrise.yml for this step please?

Here is what I have in mine

    - git::https://github.com/DamienBitrise/bitrise-test-plan-sharder.git@master:
        title: Bitrise Test Plan Sharder
        inputs:
        - target: NotesUITests
        - test_plan: Notes.xctestplan
        - scheme: "$BITRISE_SCHEME"
        - shards: '2'
        - xcode_project: Notes.xcodeproj

**Comment by moatazeldebsy** [comment]
```
- git::https://github.com/DamienBitrise/bitrise-test-plan-sharder.git@master:
        title: Bitrise Test Plan Sharder
        inputs:
        - xcode_project: Volo.xcodeproj
        - target: EarlGreyUITests
        - shards: '2'
        - scheme: EarlGreyUITests
        - test_path: ''
        - file_type: ".swift"
```
